### PR TITLE
Smile rebase

### PR DESCRIPTION
**Pull request by andrewthad**

### CODE REVIEW

**Comment by andrewthad** [comment]
I've added benchmarks, and I'm able to observe a 1.5x-3.0x speedup. The 3x speedup is against the pathological sample of 100 urls and is unlikely to observe in practice.

This still needs tests. This could be done by either writing a SMILE decoder and using quickcheck to make sure that the encoder and decoder round trip. Or it could be done by writing an integration test. I suspect that writing the decoder might be easier since it could target a similarly limited fragment of SMILE.

**Comment by Zankoku-Okuno** [comment]
I am beginning to suspect that smile uses (bigendian) VLQ instead of LEB. Testing by writing my own decoder wouldn't catch this sort of issue. The better test is definitely to write a smile->json cli program against the reference implementation.

**Comment by andrewthad** [comment]
I've got a repo at https://github.com/andrewthad/smilenumber that can generate this output. I had originally created a different application to test this, but I was not able to figure out how to get `jackson`'s `JsonParser` to return BigDecimal instead of rounding. So, I just made a different application that reads a decimal number on stdin and converts it to a smile document with just that one atom in it. For example:

```
amartin@drubot:~/Development/smilenumber$ echo '5341246532146532614022012304242.2472342657324' | java -jar /home/amartin/Development/smilenumber/target/smilenumber-1.0-jar-with-dependencies.jar | xxd
00000000: 3a29 0a00 2a9a 9301 1924 5206 323b 104e  :)..*....$R.2;.N
00000010: 6b6a 395f 0743 587e 0120 6549 0c         kj9_.CX~. eI.
```

**Comment by andrewthad** [comment]
This works now. Merging.

**Pull request merged**
